<?php
    $sSiteName = $this->getDi()->get('config')->application->siteName;
?>

<header>
    <nav class="navbar navbar-fixed-top">

        <?php if (isset($errorMessage)) : ?>
            <?php $errorCode = (isset($errorCode)) ? $errorCode : '666' ?>
            <div class="alert alert-error alert-nomargin" ng-hide="hideError">
                <a class="close" ng-click="hideError = true">&times;</a>
                Error
                #<?php echo $errorCode . ' - ' . $errorMessage; ?>
                <?php if (ENVIRONMENT == ENVIRONMENT_DEVELOPMENT) : ?>
                    <a class="icon-question-sign" ng-click="showStack = !showStack"></a>
                    <div ng-show="showStack"
                         ng-cloak>
                        <hr/>
                        <pre><?php echo (isset($stackTrace)) ? $stackTrace : 'No stack trace'; ?></pre>
                    </div>
                <?php endif; ?>
            </div>
        <?php endif; ?>

        <div class="navbar-inner">
            <?php if (!isset($showHomeLink) || $showHomeLink !== false) : ?>
                <p class="navbar-text pull-left">
                    <a href="/" title="Home"><?= $sSiteName; ?> Home</a>
                </p>
            <?php endif; ?>

            <?php if (Users::getCurrent()) : ?>
                <p class="navbar-text pull-right">
                    <ul class="nav nav-pills pull-right">
                      <li class="dropdown">
                          <a class="dropdown-toggle"
                             data-toggle="dropdown"
                             href="#">
                              My Account
                              <b class="caret"></b>
                          </a>
                          <ul class="dropdown-menu">
                              <li class="nav-header">My Account</li>
                              <li><a href="/users/myaccount" title="My Account">My Profile</a></li>
                              <li><a href="#" title="User Settings"><em>User Settings</em></a></li>
                              <li><a href="#" title="Recent Searches"><em>Recent Searches</em></a></li>
                              <li class="nav-header">Other</li>
                              <li><a href="/users/logout" title="Logout">Logout</a></li>
                          </ul>
                      </li>
                    </ul>
                </p>
            <?php else : ?>
                <p class="navbar-text pull-right">
                    <a href="/users/login" title="Sign in">Sign in</a>
                </p>
            <?php endif; ?>

            <?php if (Users::getCurrent() && Users::getCurrent()->hasSelfRole('admin')) : ?>
                <p class="navbar-text pull-right">
                    <a href="/admin/index" title="Administration">Admin</a>
                </p>
            <?php endif; ?>
        </div>
    </nav>

    <div ng-cloak class="header-content-search-area" ng-show="DisplayFlags.showSearchBar">
        <p class="navbar-text pull-left">
            <a href="/" title="Home"><?= $sSiteName; ?> home</a>
        </p>

        <p class="divset pull-left">
            <searchbox ac="/search/autocomplete" ctrlfn="doSearch(query)"></searchbox>
        </p>
        <div class="socialicons pull-right">
            <a class="fc-webicon facebook small">Like us on Facebook</a>
            <a class="fc-webicon twitter small">Follow us on Twitter</a>
            <a class="fc-webicon googleplus small">Circle us on Google Plus</a>
        </div>
    </div>

    <?php if (isset($moduleName) && isset($bLoadModuleMenu) && $bLoadModuleMenu) :
      echo "the current moduleName is ".$moduleName;
      if(empty($moduleName))
      {
        $moduleName = 'backend';
      }
      ?>
        <div class="moduleMenu header-content-search-area">
            <?php echo $this->partial('../../' . $moduleName . '/views/partials/menu'); ?>
        </div>
    <?php endif; ?>


</header>