<?php
    $sSiteName = $this->getDi()->get('config')->application->siteName;
?>

<header>
    <nav class="navbar navbar-inverse navbar-fixed-top">

        <?php if (isset($errorMessage)) : ?>
            <?php $errorCode = (isset($errorCode)) ? $errorCode : '666' ?>
            <div class="alert alert-error alert-nomargin" ng-hide="hideError">
                <a class="close" ng-click="hideError = true">&times;</a>
                Error
                #<?php echo $errorCode . ' - ' . $errorMessage; ?>
                <?php if (ENVIRONMENT == ENVIRONMENT_DEVELOPMENT) : ?>
                    <a class="icon-question-sign" ng-click="showStack = !showStack"></a>
                    <div ng-show="showStack"
                         ng-cloak>
                        <hr/>
                        <pre><?php echo (isset($stackTrace)) ? $stackTrace : 'No stack trace'; ?></pre>
                    </div>
                <?php endif; ?>
            </div>
        <?php endif; ?>

        <div class="navbar-inner">
            <?php if (!isset($showHomeLink) || $showHomeLink !== false) : ?>
                <p class="navbar-text pull-left">
                    <a href="/" title="Home"><?= $sSiteName; ?> Home</a>
                </p>
            <?php endif; ?>

            <?php if (Users::getCurrent()) : ?>
                <p class="navbar-text pull-right">
                    <a href="/users/logout" title="Sign in">Log out</a>
                </p>
                <p class="navbar-text pull-right">
                    <a href="/users/myaccount" title="My Account">My Account</a>
                </p>
            <?php else : ?>
                <p class="navbar-text pull-right">
                    <a href="/users/login" title="Sign in">Sign in</a>
                </p>
            <?php endif; ?>

            <?php if (Users::getCurrent() && Users::getCurrent()->hasSelfRole('admin')) : ?>
                <p class="navbar-text pull-right">
                    <a href="/admin" title="Administration">Administration</a>
                </p>
            <?php endif; ?>
        </div>
    </nav>

    <div ng-cloak class="header-content-search-area" ng-show="DisplayFlags.showSearchBar">
        <p class="navbar-text pull-left">
            <a href="/" title="Home"><?= $sSiteName; ?> home</a>
        </p>

        <p class="divset pull-left">
            <searchbox ac="/search/autocomplete" ctrlfn="doSearch(query)"></searchbox>
        </p>
        <div class="socialicons pull-right">
            <a class="fc-webicon facebook small">Like us on Facebook</a>
            <a class="fc-webicon twitter small">Follow us on Twitter</a>
            <a class="fc-webicon googleplus small">Circle us on Google Plus</a>
        </div>
    </div>

    <?php if (isset($moduleName) && isset($bLoadModuleMenu) && $bLoadModuleMenu) :
        ?>
        <div class="moduleMenu header-content-search-area">
          <ul class="nav nav-pills">
            <li class="dropdown">
              <a class="dropdown-toggle"
                 data-toggle="dropdown"
                 href="#">
                User management
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li class="nav-header">Users</li>
                <li><a href="/admin/users/list" title="List / Search Accounts">List / Search Accounts</a></li>
                <li><a href="/admin/users/upsert" title="Add New Account">Add New Account</a></li>
                <li class="nav-header">Contacts</li>
                <li><a href="/admin/contacts/list" title="List / Search Contacts">List / Search Contacts</a></li>
                <li><a href="/admin/contacts/upsert" title="Add New Contact">Add New Contact</a></li>
                <li class="nav-header">Account Roles</li>
                <li><a href="/admin/roles/list" title="List / Search Roles">List / Search Roles</a></li>
                <li><a href="/admin/roles/upsert" title="Add New Role">Add New Role</a></li>
              </ul>
            </li>

            <li class="dropdown">
              <a class="dropdown-toggle"
                 data-toggle="dropdown"
                 href="#">
                Tags Management
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><a href="/admin/tag/listother" title="Entities / Tag types">Entities / Tag Types</a></li>
                <li><a href="/admin/tag/list" title="Tags">List Tags</a></li>
                <li><a href="/admin/tag/upsert" title="Tags">Add New Tag</a></li>
              </ul>
            </li>

            <li class="dropdown">
              <a class="dropdown-toggle"
                 data-toggle="dropdown"
                 href="#">
                Emails
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><a href="/admin/emails" title="Emails Dashboard">Dashboard</a></li>
                <li><a href="/admin/emails/list" title="List / Search Email Templates">List / Search Email Templates</a></li>
                <li><a href="/admin/emails/upsert" title="Add new Template">Add New Template</a></li>
                <li><a href="/admin/emails/listq" title="List / Search Queue / Archive">List / Search Queue-Archive</a></li>
              </ul>
            </li>

            <li class="dropdown">
              <a class="dropdown-toggle"
                 data-toggle="dropdown"
                 href="#">
                Geo
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><a href="/admin/geo" title="Geo dashboard">Geo Dashboard</a></li>
                <li class="nav-header">Countries</li>
                <li><a href="/admin/geo/countrieslist" title="List Countries">List Countries</a></li>
                <li><a href="/admin/geo/upsertcountry" title="Add Country">Add Country</a></li>
                <li class="nav-header">Cities</li>
                <li><a href="/admin/geo/citieslist" title="List Cities">List Cities</a></li>
                <li><a href="/admin/geo/upsertcity" title="Add City">Add City</a></li>
                <li class="nav-header">States</li>
                <li><a href="/admin/geo/stateslist" title="List States">List States</a></li>
                <li><a href="/admin/geo/upsertstate" title="Add State">Add State</a></li>
              </ul>
            </li>

            <li class="dropdown">
              <a class="dropdown-toggle"
                 data-toggle="dropdown"
                 href="#">
                Misc
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><a href="/admin/misc/usersettings" title="User Settings">User Settings</a></li>
                <li><a href="/admin/misc/recentsearches" title="Recent Searches">Recent Searches</a></li>
                <li class="nav-header">Other</li>
                <li><a href="/admin/misc/phpinfo" title="Php Info">Php Info</a></li>
              </ul>
            </li>
          </ul>
        </div>
    <?php endif; ?>


</header>